[package]
name = "bejeweled"
version = "0.1.0"
authors = ["Fredrik <fredrik@parity.io>"]

[dependencies]
rand = "0.3"
time = "0.1"
ansi_term = "0.9"

[lib]
name = "bejeweled"

[[bin]]
name = "bejeweled-cli"
path = "src/main.rs"
