[package]
name = "leaderboard"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
futures = "0.1.11"
hyper = "0.11.2"
pretty_env_logger = "0.1.1"
parking_lot = "0.4.8"
url = "1.5.1"
