[package]
name = "roguelike"
version = "0.1.0"
authors = ["Fredrik <fredrik@parity.io>"]

[dependencies]
termion = "1.3"

[lib]
name = "roguelike"

[[bin]]
name = "roguelike-cli"
path = "src/main.rs"
